# Generated by Django 5.1.4 on 2024-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_income_amount_alter_income_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
